### ISSUE TITLE
Maven?

### ISSUE THREAD

**Issue by jmtd** [jmtd/wadc#7]
Should we use a build system other than a makefile? At least one person has erroneously thought that this is a UNIX-only project because of the Makefile. Moving to maven would mean we would avoid rebuilding all the java files whenever one changed (not a great hardship) but might also mean we could more easily bundle other libraries like Apache commons stuff. That in particular might be useful for CLI and command-line argument handling, but perhaps also for i18n stuff. Not sure. Oh, either way, we should probably put HTML in the distribution ZIP.

Paging @jonrimmer, I would love some advice :)
1. Maven? or gradle? Neither?
2. [here's an initial maven-ifiation](https://github.com/jmtd/wadc/commit/76e2f62502073f8336072224a06c8a2fcefb709a). Does it look sane?
3. [here's a customized source location change](https://github.com/jmtd/wadc/commit/1a08a2cd4be079553de84565dda2d6a9d8f0d403). Is this the road to madness?

**Comment by jonrimmer** [comment]
1. I think using a Java build system is sensible. I'm more familiar with Gradle but have no objection to using Maven.
2. That said, I do think we should keep the conventional folder structure if possible. It's what most tools expect, and it helps people know where to find tests, resources, etc. With the package structure in the root, I'm not sure where we'd put unit tests?

**Comment by jmtd** [comment]
Thanks for the feedback! I haven't use gradle before, or really maven either. Since I've done the maven work I'll merge the former, but I'll take your advice and ditch the latter :)
